### ISSUE TITLE
Distance is almost random when using a BT dongle from Broadcomm

### ISSUE THREAD

**Issue by lapilesos** [huysentruitw/win-beacon#28] opened 2017-04-19 16:45 UTC
Hi,

I've tested this library with Oreco BT Dongle - works perfect. Precision is within of my assumptions. BT Dongle from Broadcomm returns some perverse results. Distances are almost random. They still remain stable if beacon stays at same place. But if I start to move it - distances sometimes jump within +-5m.

What kind of information you need about this issue - or I have to skip Broadcomm dongle and hug that one, that works?  

Addition: On both tested PC (Windows 8 and 10) minimal distance that comes from WInBeacon is 2.51m. Even if I put the Beacon on top of the dongle. 

WbR,
Andrew

**Comment by huysentruitw** [comment] 2017-04-19 21:11
The problem is that the distance is calculated from the dB value sent by the beacon which reflects the transmission power of the dongle and isn't very precise (precision is 1dB). A change of 1 dB reflects a change of multiple meters in approximated distance.

So depending on your requirements, you might want to choose the brand/dongle that gives you the most stable results.

**Comment by lapilesos** [comment] 2017-04-19 21:29
I know about "precison" of RSSI/Power calculation. Somehow it's a tradeoff for cheap radio and lack of additional sensors and power. Still its strange that one BT dongle works and I "see" movement of beacon from and to dongle. On the other side - BT Dongle from Broadcomm works veeeeeery unprecise. I've monitored rssi values and they was same from 10 cm to approximate 1.5m. This leads me to idea - that Broadcomm dongle recieve/retranslate datagrams in non conform state. Still I'm lucking experience with different BT dongle. Till now i've tested 2 - one of them ( dirty noname from nowhere) works good. And branded one - didnt work at all. 
For reference:
Broadcom : https://www.amazon.de/gp/product/B015R7OA1U/ref=oh_aui_detailpage_o02_s00?ie=UTF8&psc=1
Orico:https://www.amazon.de/gp/product/B01C6WMK2K/ref=oh_aui_detailpage_o05_s00?ie=UTF8&psc=1

**Comment by huysentruitw** [comment] 2017-06-29 13:27
Closing this because this is hardware related.

**Closed by huysentruitw** 2017-06-29 13:27 UTC
Labels: question
